<a href="https://colab.research.google.com/github/bee-llel/Machine-Learning/blob/master/RecurrentNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [394]:
#librairy:
import pandas as pd # used to manipulate the data 
import numpy as np
import scipy as sp 
from numpy import *


In [451]:
import random as rd 
from random import *

#######################################
# DATA : random binary number 
X_train = []
X_test = [] 
y_train = []
y_test = [] 

for i in range(30) :
  X = [randint(0, 1) for i in range(10) ]
  X_train.append(X)
  y_train.append(sum(X))

for i in range(10):
  X = [randint(0, 1) for i in range(10) ]
  X_test.append(X)
  y_test.append(sum(X))

X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

y_train.reshape((30,1))
print(X_train)
print(y_train)
print(y_train.shape)

[[0 1 1 0 0 1 0 0 0 0]
 [0 1 0 1 1 0 1 0 1 1]
 [1 1 0 1 1 0 1 1 1 0]
 [0 0 1 1 1 0 0 1 0 0]
 [0 0 1 0 0 1 1 0 0 0]
 [1 0 0 1 0 0 0 1 0 0]
 [1 0 0 1 0 1 1 0 1 0]
 [0 1 0 0 0 1 1 1 0 0]
 [1 1 1 1 1 1 0 0 1 1]
 [0 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 0 1 0]
 [0 1 1 1 1 0 0 0 0 0]
 [1 1 1 0 1 0 0 1 0 1]
 [0 1 0 1 1 1 1 1 0 1]
 [1 0 0 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 1 1 0 1]
 [1 1 1 0 1 1 0 0 1 0]
 [0 0 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 0]
 [1 0 0 0 0 1 1 0 0 0]
 [1 0 0 0 0 1 1 1 0 1]
 [1 0 0 0 0 0 1 1 1 0]
 [1 1 1 0 1 1 0 0 0 0]
 [1 0 0 0 1 0 1 0 1 0]
 [1 1 0 1 0 0 0 1 0 0]
 [1 1 0 0 0 1 0 0 0 1]
 [0 0 0 1 1 1 1 1 1 0]
 [0 1 1 1 0 0 0 1 0 1]
 [0 1 1 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0]]
[3 6 7 4 3 3 5 4 8 1 7 4 6 7 3 5 6 7 3 3 5 4 5 4 4 4 6 5 4 2]
(30,)


In [452]:
#################################
######################################
#allows us to always have the same result when calling a random function
#np.random.seed(23)
# VARIABLE DECLARATION:
###################################################
#basic number 
#T = lenght of the sequence 
T = 10
#
#I = data size 
I = 30
#
#J = output dimension = 1 not needed
J = 1
#
#K = number of hidden neuron  not needed
###################################################
# data: imput X = X_train and output y =  y_train:
# dimension : X  : I * T

X = X_train

# dimension : y : I * J = 30*1

y = y_train

###################################################
# activation function F = identity 

# dimension : same as X i think 
# we will initialize it's value to one to start 
F = np.zeros((I,T))
#our estimation G is the last F is the sequence this time since there is no activation function
#we will initialize it to zero.

G = np.zeros((I))

###################################################
#Weight:

# Vx:  weight of X 
#dimension : scalar

Vx = np.random.uniform(0, 1)


# Vf: weight of F 
#dimension : scalar

Vf = np.random.uniform(0, 1)


##################################################
#learning rate aplha

alpha = 0.1


print(F.shape)
print(G.shape)
print(y.shape)
print(Vx)
print(Vf)

(30, 10)
(30,)
(30,)
0.05326709464893753
0.3454784779791955


In [453]:
def SSE(A,B):
 # E = 0.5*(((A-B)).sum())**
  E = 1 / 2 * np.sum((A - B)**2)
  return E

In [454]:
###################################################
#Forward propagation 
def forwardprop(X,y,Vx,Vf,T,I):
  for t in range(T-1):
    for i in range(I):
        F[i][t+1] = F[i][t] * Vf + X[i][t] * Vx
        G[i] = F[i][T-1] * Vf + X[i][T-1] * Vx   

            
  
  return(G)

In [455]:
###################################################
# backpropagation
def backprop(G,y,Vx,Vf,T,I,alpha):
  for t in range(T):
    for i in range(I):
      Vx = Vx - alpha * (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))


  for t in range(T-1):    
    for i in range(I):
      Vf = Vf - alpha *  (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))


      
  return(Vx,Vf)


In [462]:
############################################
#RNN with backprop
Vxbp = Vx*0.001
Vfbp = Vf*0.001
alphabp = alpha * 0.001
for i in range(1000):
  G = forwardprop(X,y,Vxbp,Vfbp,T,I)        
  (Vxbp,Vfbp) = backprop(G,y,Vxbp,Vfbp,T,I,alphabp)
  print(SSE(y,G))

357.9997162933748
357.71894320881665
357.4386752883845
357.15891162319224
356.87965130598866
356.60089343115516
356.3226370947026
356.044881394268
355.7676254291119
355.49086830011584
355.2146091097788
354.9388469622143
354.6635809631481
354.38881021991483
354.11453384145506
353.8407509383126
353.56746062263164
353.2946620081538
353.02235421021516
352.7505363457434
352.4792075332553
352.2083668928533
351.9380135462231
351.6681466166307
351.3987652289192
351.12986850950676
350.8614555863829
350.5935255891062
350.3260776488013
350.05911089815606
349.79262447141906
349.5266175043961
349.2610891344481
348.9960385004881
348.7314647429782
348.4673670039269
348.20374442688694
347.9405961569513
347.6779213407515
347.4157191264541
347.15398866375875
346.89272910389457
346.6319395996179
346.3716193052094
346.1117673764714
345.8523829707251
345.59346524680774
345.33501336507015
345.0770264873736
344.81950377708745
344.5624443990866
344.3058475197479
344.04971230694866
343.7940379300629
343.538823

In [229]:
print(X[:][3])
print(X[:,3])

[0 0 1 1 0 0 0 1 0 0]
[1 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0]


In [ ]:
for k in range(K+1):
    for j in range(J):
      W[k][j] = W[k][j] - 0.01*((G[:,j]-y[:,j]) * G[:,j] * (np.ones(G.shape)[:,j]-G[:,j]) * F_b[:,k]).sum(axis =0)

In [127]:
np.random.seed(15)
        #fixing the variables:
        #number of element

        #input data
X=X_train        
I=len(X)
        #length of sequence
T=len(X[0])

        #expected result
Y=y_train
        #learning rate
alpha=0.1
        #weight of the loop
w=np.random.rand()
        #weight of the input
v=w
        #the intermediate values created by the RNN f[0] being 0 as there is no data created before the start
f=np.zeros((I,T))
g=np.zeros((I))
        #variables used for resilient propagation
Delta_v=0.001
Delta_w=0.001
sign_v=1
sign_w=1
sign_prev_v=0
sign_prev_w=0
        #variables for gardient clipping
n=0.2
        
    #the forward propagation


            

print(g.shape)            
print(f.shape)
print(g)
print(I)
print(T)

(30,)
(30, 10)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
30
10


In [129]:
for t in range(T):
        for i in range(I):
            if(t!=T-1):
              f[i,t+1] = f[i,t] * w + X[i,t] * v
            else:
              g[i] = f[i,t] * w + X[i,t] * v
print(g)              

[2.63461944 2.02353903 2.40381396 1.68645673 1.22920911 2.41130012
 1.54029932 3.04438974 3.12286968 1.31600745 3.31298477 2.65832014
 1.66345861 0.8722195  2.81713063 2.96063666 1.8343965  2.87323479
 3.33476419 1.79568356 2.65007187 2.45494387 1.59839624 1.5070006
 1.41285117 1.93195915 1.6814462  2.29301212 3.31386283 1.47508056]


In [128]:
for t in range(T-1):
        for i in range(I):
              f[i,t+1] = f[i,t] * w + X[i,t] * v
              g[i] = f[i,T-1] * w + X[i,T-1] * v

print(g)

[2.63461944 2.02353903 2.40381396 1.68645673 1.22920911 2.41130012
 1.54029932 3.04438974 3.12286968 1.31600745 3.31298477 2.65832014
 1.66345861 0.8722195  2.81713063 2.96063666 1.8343965  2.87323479
 3.33476419 1.79568356 2.65007187 2.45494387 1.59839624 1.5070006
 1.41285117 1.93195915 1.6814462  2.29301212 3.31386283 1.47508056]
