<a href="https://colab.research.google.com/github/bee-llel/Machine-Learning/blob/master/RecurrentNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
#librairy:
import pandas as pd # used to manipulate the data 
import numpy as np
import scipy as sp 
from numpy import *


In [27]:

import random as rd 
from random import *

#######################################
# DATA : random binary number 
X_train = []
X_test = [] 
y_train = []
y_test = [] 

for i in range(30) :
  X = [randint(0, 1) for i in range(10) ]
  X_train.append(X)
  y_train.append(sum(X))

for i in range(10):
  X = [randint(0, 1) for i in range(10) ]
  X_test.append(X)
  y_test.append(sum(X))

X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

y_train.reshape((30,1))
print(X_train)
print(y_train)
print(y_train.shape)

[[0 1 1 0 1 1 1 1 1 0]
 [0 0 1 0 0 0 1 0 0 1]
 [0 0 1 1 0 0 1 0 1 1]
 [1 0 0 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 0 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 1 0 0 1 0 0 0]
 [1 0 0 1 1 1 1 0 0 0]
 [1 1 0 0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1 1 1 1]
 [1 1 0 0 1 1 0 1 1 1]
 [1 0 0 1 0 1 0 1 0 0]
 [1 0 1 1 0 1 0 1 1 0]
 [1 0 0 1 1 1 0 1 1 1]
 [0 0 1 0 1 0 1 0 1 1]
 [1 0 1 0 1 1 1 0 1 1]
 [0 1 0 1 1 1 1 0 1 1]
 [1 0 1 0 0 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1 1]
 [0 0 0 1 1 0 0 1 1 1]
 [0 1 0 1 0 0 1 1 1 0]
 [1 1 0 1 1 1 0 1 1 0]
 [0 1 1 1 0 1 0 0 0 0]
 [0 1 0 1 0 0 1 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 1 1 0 1 0 0]
 [0 1 1 0 1 1 0 0 1 0]
 [0 1 1 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 0 0 1 0]
 [1 0 1 1 1 0 0 1 0 0]]
[7 3 5 5 4 7 2 5 6 6 7 4 6 7 5 7 7 5 7 5 5 7 4 4 2 4 5 4 2 5]
(30,)


In [38]:
#################################
######################################
#allows us to always have the same result when calling a random function
np.random.seed(23)
# VARIABLE DECLARATION:
###################################################
#basic number 
#T = lenght of the sequence 
T = 10
#
#I = data size 
I = 30
#
#J = output dimension = 1 not needed
J = 1
#
#K = number of hidden neuron  not needed
###################################################
# data: imput X = X_train and output y =  y_train:
# dimension : X  : I * T

X = X_train

# dimension : y : I * J = 30*1

y = y_train

###################################################
# activation function F = identity 

# dimension : same as X i think 
# we will initialize it's value to one to start 
F = np.zeros((I,T))
#our estimation G is the last F is the sequence this time since there is no activation function
#we will initialize it to zero.

G = np.zeros((I))

###################################################
#Weight:

# Vx:  weight of X 
#dimension : scalar

Vx = np.random.uniform(0, 1)


# Vf: weight of F 
#dimension : scalar

Vf = np.random.uniform(0, 1)


##################################################
#learning rate aplha

alpha = 0.1

##################################################
# resillient propagation variable:
nN = 0.5
nP = 1.2
Dxinit = 0.001
Dfinit = 0.001

previousSign = 1
currentSign = 1




print(F.shape)
print(G.shape)
print(y.shape)
print(Vx)
print(Vf)

(30, 10)
(30,)
(30,)
0.5172978838465893
0.9469626038148141


In [31]:
#################################################
# useful function
def SSE(A,B):
 # E = 0.5*(((A-B)).sum())**
  E = 1 / 2 * np.sum((A - B)**2)
  return E

def SIGN(A):
  x = 0
  if A >=0:
    x = 1
  else:
    x = -1
  return x 

In [32]:
###################################################
#Forward propagation 
def forwardprop(X,y,Vx,Vf,T,I):
  for t in range(T-1):
    for i in range(I):
        F[i][t+1] = F[i][t] * Vf + X[i][t] * Vx
        G[i] = F[i][T-1] * Vf + X[i][T-1] * Vx   

            
  
  return(G)

In [33]:
###################################################
# backpropagation
# we have to be mindful of the difference between T 
# and in range(T) because in the second case it is starting from 0 to T-1
# so we have to adapt our notation 
def backprop(G,y,Vx,Vf,T,I,alpha):
  for t in range(T):
    for i in range(I):
      Vx = Vx - alpha * (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))


  for t in range(T-1):    
    for i in range(I):
      Vf = Vf - alpha *  (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))


      
  return(Vx,Vf)


In [37]:
#################################################
# Resillient propagation
def resillientprop(G,y,Vx,Vf,T,I,nN,nP,Dxinit,Dfinit):

#################################################
# Vx :
  Dx = Dxinit
  gradX = 0
  currentSIGNX = 1
  previousSIGNX = 1
  for t in range(T):
    for i in range(I):
        gradX = gradX +  (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))

  currentSIGNX = SIGN(gradX) 

  if (currentSIGNX == previousSIGNX):
    Dx = Dx * nP
  else:
    Dx = Dx * nN
# update Vx

  Vx = Vx - Dx * currentSIGNX
  previousSIGNX = currentSIGNX 

#################################################
# Vf :
  Df = Dfinit
  gradF = 0
  currentSIGNF = 1
  previousSIGNF = 1

  for t in range(T-1):    
    for i in range(I):
      gradF = gradF + (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))
  
  currentSIGNF = SIGN(gradF) 

  if (currentSIGNF == previousSIGNF):
    Df = Df * nP
  else:
    Df = Df * nN

# update Vf
  Vf = Vf - Df * currentSIGNF
  previousSIGNF = currentSIGNF 

  return(Vx,Vf)

In [40]:
############################################
#RNN with backprop

# weight for the backprop
Vxbp = np.random.uniform(0, 1)*0.001
Vfbp = np.random.uniform(0, 1)*0.001
#learning rate for the backprop
alphabp = alpha * 0.001

# the backpropagation converge for extremely small value of alpha 
#and extremely small weight initializiation
print("Error before using our RNN with backpropragation", SSE(y,G))
for i in range(2000):
  G = forwardprop(X,y,Vxbp,Vfbp,T,I)        
  (Vxbp,Vfbp) = backprop(G,y,Vxbp,Vfbp,T,I,alphabp)
print("Error after using our RNN with backpropragation",SSE(y,G))

Error before using our RNN with backpropragation 0.001449979106958384
Error after using our RNN with backpropragation 0.017323363445311858


In [39]:
############################################
# RNN with resillient prop

print("Error before using our RNN with resillient propragation", SSE(y,G))
for i in range(2000):
  G = forwardprop(X,y,Vx,Vf,T,I)        
  (Vx,Vf) = resillientprop(G,y,Vx,Vf,T,I,nN,nP,Dxinit,Dfinit)
print("Error after using our RNN with resillient backpropragation",SSE(y,G))

Error before using our RNN with resillient propragation 421.0
Error after using our RNN with resillient backpropragation 0.001449979106958384


In [ ]:
for k in range(K+1):
    for j in range(J):
      W[k][j] = W[k][j] - 0.01*((G[:,j]-y[:,j]) * G[:,j] * (np.ones(G.shape)[:,j]-G[:,j]) * F_b[:,k]).sum(axis =0)

In [127]:
np.random.seed(15)
        #fixing the variables:
        #number of element

        #input data
X=X_train        
I=len(X)
        #length of sequence
T=len(X[0])

        #expected result
Y=y_train
        #learning rate
alpha=0.1
        #weight of the loop
w=np.random.rand()
        #weight of the input
v=w
        #the intermediate values created by the RNN f[0] being 0 as there is no data created before the start
f=np.zeros((I,T))
g=np.zeros((I))
        #variables used for resilient propagation
Delta_v=0.001
Delta_w=0.001
sign_v=1
sign_w=1
sign_prev_v=0
sign_prev_w=0
        #variables for gardient clipping
n=0.2
        
    #the forward propagation


            

print(g.shape)            
print(f.shape)
print(g)
print(I)
print(T)

(30,)
(30, 10)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
30
10


In [129]:
for t in range(T):
        for i in range(I):
            if(t!=T-1):
              f[i,t+1] = f[i,t] * w + X[i,t] * v
            else:
              g[i] = f[i,t] * w + X[i,t] * v
print(g)              

[2.63461944 2.02353903 2.40381396 1.68645673 1.22920911 2.41130012
 1.54029932 3.04438974 3.12286968 1.31600745 3.31298477 2.65832014
 1.66345861 0.8722195  2.81713063 2.96063666 1.8343965  2.87323479
 3.33476419 1.79568356 2.65007187 2.45494387 1.59839624 1.5070006
 1.41285117 1.93195915 1.6814462  2.29301212 3.31386283 1.47508056]


In [128]:
for t in range(T-1):
        for i in range(I):
              f[i,t+1] = f[i,t] * w + X[i,t] * v
              g[i] = f[i,T-1] * w + X[i,T-1] * v

print(g)

[2.63461944 2.02353903 2.40381396 1.68645673 1.22920911 2.41130012
 1.54029932 3.04438974 3.12286968 1.31600745 3.31298477 2.65832014
 1.66345861 0.8722195  2.81713063 2.96063666 1.8343965  2.87323479
 3.33476419 1.79568356 2.65007187 2.45494387 1.59839624 1.5070006
 1.41285117 1.93195915 1.6814462  2.29301212 3.31386283 1.47508056]
