<a href="https://colab.research.google.com/github/bee-llel/Machine-Learning/blob/master/RecurrentNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
#librairy:
import pandas as pd # used to manipulate the data 
import numpy as np
import scipy as sp 
from numpy import *


In [47]:
import random as rd 
from random import *
#allows us to always have the same result when calling a random function
np.random.seed(23)
# this small part was made with another group in class ( it's the lab) so it's the same as a few classmate.

#######################################
# DATA : random binary number 

X_train = []
X_test = [] 
y_train = []
y_test = [] 

for i in range(30) :
  X = [randint(0, 1) for i in range(10) ]
  X_train.append(X)
  y_train.append(sum(X))

for i in range(10):
  X = [randint(0, 1) for i in range(10) ]
  X_test.append(X)
  y_test.append(sum(X))

X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

y_train.reshape((30,1))
print(X_train)
print(y_train)
print(y_train.shape)

[[1 0 1 0 1 0 1 1 1 1]
 [0 1 0 0 1 1 0 1 0 1]
 [1 1 0 0 1 1 1 0 0 1]
 [0 1 1 1 0 1 1 0 0 0]
 [1 0 1 0 1 0 0 0 0 1]
 [0 1 0 1 1 1 0 0 0 1]
 [0 1 0 0 0 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 1]
 [0 1 0 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 0 1 0]
 [0 0 0 0 1 1 0 1 1 0]
 [0 1 1 1 0 1 1 1 1 1]
 [0 1 1 1 0 0 1 1 0 1]
 [0 0 1 1 1 1 1 0 0 1]
 [0 1 1 0 1 0 0 1 1 1]
 [1 0 0 0 1 0 0 1 0 0]
 [1 0 1 1 1 0 0 1 1 0]
 [0 1 0 1 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 1 1 0]
 [0 1 0 1 1 0 0 1 0 0]
 [0 0 0 1 1 1 1 0 1 1]
 [0 1 0 0 1 1 0 1 1 0]
 [0 1 1 0 1 1 1 0 1 1]
 [0 1 0 0 1 0 0 0 1 1]
 [0 1 0 1 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 1 0 1 0 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0]]
[7 5 6 5 4 5 4 7 8 7 4 8 6 6 6 3 6 4 6 4 6 5 7 4 2 5 3 3 2 2]
(30,)


In [48]:
#################################
######################################
# VARIABLE DECLARATION:
###################################################
#basic number 
#T = lenght of the sequence 
T = 10
#
#I = data size 
I = 30
#
#J = output dimension = 1 not needed
J = 1
#
#K = number of hidden neuron  not needed
###################################################
# data: imput X = X_train and output y =  y_train:
# dimension : X  : I * T

X = X_train

# dimension : y : I * J = 30*1

y = y_train

###################################################
# activation function F = identity 

# dimension : same as X i think 
# we will initialize it's value to one to start 
F = np.zeros((I,T))
#our estimation G is the last F is the sequence this time since there is no activation function
#we will initialize it to zero.

###################
# G for backprop
G = np.zeros((I))

###################################################
#Weight:
# Vf: weight of F 
#dimension : scalar
# Vx:  weight of X 
#dimension : scalar

# weight for the backprop
Vxbp = np.random.uniform(0, 1)*0.001
Vfbp = np.random.uniform(0, 1)*0.001

# weight for the resillientprop
Vx = np.random.uniform(0, 1)
Vf = np.random.uniform(0, 1)

##################################################
#learning rate aplha
#learning rate for the backprop
alpha = 0.1
alphabp = alpha * 0.001


##################################################
# resillient propagation variable:
nN = 0.5
nP = 1.2
Dxinit = 0.001
Dfinit = 0.001

previousSign = 1
currentSign = 1




print(F.shape)
print(G.shape)
print(y.shape)
print(Vx)
print(Vf)

(30, 10)
(30,)
(30,)
0.7654597593969069
0.2823958439671127


In [49]:
#################################################
# useful function
def SSE(A,B):
 # E = 0.5*(((A-B)).sum())**
  E = 1 / 2 * np.sum((A - B)**2)
  return E

def SIGN(A):
  x = 0
  if A >=0:
    x = 1
  else:
    x = -1
  return x 

In [50]:
###################################################
#Forward propagation 
def forwardprop(X,y,Vx,Vf,T,I,F,G):
  for t in range(T-1):
    for i in range(I):
        F[i][t+1] = F[i][t] * Vf + X[i][t] * Vx
        G[i] = F[i][T-1] * Vf + X[i][T-1] * Vx   

            
  
  return(G)

In [51]:
###################################################
# backpropagation
# we have to be mindful of the difference between T 
# and in range(T) because in the second case it is starting from 0 to T-1
# so we have to adapt our notation 
def backprop(G,y,Vx,Vf,T,I,alpha):
  for t in range(T):
    for i in range(I):
      Vx = Vx - alpha * (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))


  for t in range(T-1):    
    for i in range(I):
      Vf = Vf - alpha *  (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))


      
  return(Vx,Vf)


In [52]:
#################################################
# Resillient propagation
def resillientprop(G,y,Vx,Vf,T,I,nN,nP,Dxinit,Dfinit):

#################################################
# Vx :
  Dx = Dxinit
  gradX = 0
  currentSIGNX = 1
  previousSIGNX = 1
  for t in range(T):
    for i in range(I):
        gradX = gradX +  (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))

  currentSIGNX = SIGN(gradX) 

  if (currentSIGNX == previousSIGNX):
    Dx = Dx * nP
  else:
    Dx = Dx * nN
# update Vx

  Vx = Vx - Dx * currentSIGNX
  previousSIGNX = currentSIGNX 

#################################################
# Vf :
  Df = Dfinit
  gradF = 0
  currentSIGNF = 1
  previousSIGNF = 1

  for t in range(T-1):    
    for i in range(I):
      gradF = gradF + (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))
  
  currentSIGNF = SIGN(gradF) 

  if (currentSIGNF == previousSIGNF):
    Df = Df * nP
  else:
    Df = Df * nN

# update Vf
  Vf = Vf - Df * currentSIGNF
  previousSIGNF = currentSIGNF 

  return(Vx,Vf)

In [64]:
#################################################
# gradient clipping

def gradientclip(G,y,Vx,Vf,T,I,N,alpha):
  gradX = 0
  for t in range(T):
    for i in range(I):
        gradX = gradX +  (G[i] - y[i]) * X[i][t] * (Vf**(T-(t+1)))

  if abs(gradX) > N:
    gradX = N
  
  Vx = Vx - (alpha * gradX)


  gradF = 0
  for t in range(T):
    for i in range(I):
        gradF = gradF +  (G[i] - y[i]) * F[i][t] * (Vf**(T-(t+1)))


  if abs(gradF) > N:
    gradF = N
  
  Vf = Vf - (alpha * gradF)

  return(Vx,Vf)

In [57]:
############################################
#RNN with backprop

# we re-initialize G and F so you can launch the other propagation 
F = np.zeros((I,T))
G = np.zeros((I))

# weight for the backprop
Vxbp = np.random.uniform(0, 1)*0.001
Vfbp = np.random.uniform(0, 1)*0.001


# the backpropagation converge for extremely small value of alpha 
#and extremely small weight initializiation
print("Error before using our RNN with backpropragation", SSE(y,G))
for i in range(2000):
  G = forwardprop(X,y,Vxbp,Vfbp,T,I,F,G)        
  (Vxbp,Vfbp) = backprop(G,y,Vxbp,Vfbp,T,I,alphabp)
print("Error after using our RNN with backpropragation",SSE(y,G))

Error before using our RNN with backpropragation 418.0
Error after using our RNN with backpropragation 0.49317710278688837


In [58]:
############################################
# RNN with resillient prop
F = np.zeros((I,T))
G = np.zeros((I))


# weight for the resillientprop
Vx = np.random.uniform(0, 1)
Vf = np.random.uniform(0, 1)

print("Error before using our RNN with resillient propragation", SSE(y,G))
for i in range(2000):
  G = forwardprop(X,y,Vx,Vf,T,I,F,G)        
  (Vx,Vf) = resillientprop(G,y,Vx,Vf,T,I,nN,nP,Dxinit,Dfinit)
print("Error after using our RNN with resillient backpropragation",SSE(y,G))

Error before using our RNN with resillient propragation 418.0
Error after using our RNN with resillient backpropragation 0.017584838879619178


In [65]:
############################################
#RNN with gradient clipping

# we re-initialize G and F so you can launch the other propagation 
F = np.zeros((I,T))
G = np.zeros((I))

# learning rate alpha
alpha = 0.1

# value for clipping N:
N = 0.3

# weight for the backprop
Vxclip = np.random.uniform(0, 1)
Vfclip = np.random.uniform(0, 1)


# the backpropagation converge for extremely small value of alpha 
#and extremely small weight initializiation
print("Error before using our RNN with backpropragation", SSE(y,G))
for i in range(2000):
  G = forwardprop(X,y,Vxbp,Vfbp,T,I,F,G)        
  (Vxclip,Vfclip) = gradientclip(G,y,Vxbp,Vfbp,T,I,N,alpha)
print("Error after using our RNN with backpropragation",SSE(y,G))

Error before using our RNN with backpropragation 418.0
Error after using our RNN with backpropragation 0.4907845975450945
