<a href="https://colab.research.google.com/github/bee-llel/Machine-Learning/blob/master/Hidden_Markov_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,0,0,0],[0.2,0.3,0.1,0.4],[0.2,0.5,0.2,0.1],[0.7,0.1,0.1,0.1]])
B = np.array([[1,0,0,0,0],[0,0.3,0.4,0.1,0.2],[0,0.1,0.1,0.7,0.1],[0,0.5,0.2,0.1,0.2]])
print(B)


[[1.  0.  0.  0.  0. ]
 [0.  0.3 0.4 0.1 0.2]
 [0.  0.1 0.1 0.7 0.1]
 [0.  0.5 0.2 0.1 0.2]]


Initialization of alpha:

In [3]:
b = np.shape(B)
T = b[1] #T=5
J = b[0]#J=4

#Initialisation
alpha = np.zeros((J,T))
alpha

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
def forward(A,B):
    b = np.shape(B)
    T = b[1] #T=5
    J = b[0]#J=4
    alpha = np.zeros((J,T))
    alpha[1,0]=1 #Initial state
    k_array = np.array([0,1,3,2,0])
    
    for t in range(1,T):
        for j in range(0,J):
            somme = 0
            k = k_array[t]
            for i in range(0,J):
                somme += alpha[i,t-1]*A[i,j]*B[j,k]
            alpha[j,t] = somme
    return alpha

In [5]:
alpha = forward(A,B)
alpha

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.8218e-03],
       [1.0000e+00, 9.0000e-02, 5.2000e-03, 5.1920e-03, 0.0000e+00],
       [0.0000e+00, 1.0000e-02, 2.1700e-02, 5.4300e-04, 0.0000e+00],
       [0.0000e+00, 2.0000e-01, 5.7000e-03, 9.6400e-04, 0.0000e+00]])